apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuploy-web-client
spec:
  selector:
    matchLabels:
      app: kuploy-web-client
  template:
    metadata:
      labels:
        app: kuploy-web-client
    spec:
      containers:
        - name: kuploy-web
          image: docku.ddns.net/kuploy/kuploy-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory : 300Mi
