apiVersion: v1
kind: Service
metadata:
  name: kuploy-web-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.251
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: kuploy-web-client
