name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TAG : $(date +%s)
      run: |
        docker login docku.ddns.net -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t kuploy-web ./webFront

        docker tag kuploy-web docku.ddns.net/kuploy/kuploy-web:$TAG
        docker push docku.ddns.net/kuploy/kuploy-web:$TAG
        
        # IMAGE_NAME="kuploy/kuploy-web"
        # IMAGE_TAG="${{ github.sha }}"
        
        # echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
        # docker buildx create --use
        # docker buildx build -t "$IMAGE_NAME:$IMAGE_TAG" --push ./webFront
