name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TAG : $(date +%s)
      run: |
        docker build ./webFront --file webFront/Dockerfile --tag kuploy-web
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag kuploy-web kuploy/kuploy-web
        docker push kuploy/kuploy-web
